---
- name:  Check package version playbook
  hosts: demo

  tasks:
    - name: Check version of docker package
      yum:
        list:  docker
      register: docker_pkg

    - debug:
        var: docker_pkg
