# Will patch or install the latest docker version

---
- name:  Install or patch to latest version
  hosts: demo
  become:  true

  tasks:
    - name: Install or patch to latest version
      yum:
        name:  docker
        state:  latest
