# Will patch docker to a specific version that is not the latest

---
- name:  Patch package if correct version not installed
  hosts: demo
  become:  true

  tasks:
    - name: Install specific version of docker package
      yum:
        name:  docker
        state:  latest
