---
- name:  Patch package if correct version not installed
  hosts: demo

  tasks:
    - name: Install specific version of docker package
      yum:
        name:  docker-1.12.5-14.el7.centos.x86_64
        state:  present
      
