# Remove the docker package

---
- name:  Removal of docker package and dependencies
  hosts: demo
  become:  true

  tasks:
    - name: Removal docker and dependencies
      yum:
        name:  docker, docker-common
        state:  absent
